
name: wifiscanner
description: "wifi scanner"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wifi_scan: ^0.4.1+2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#121212"
  image: assets/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
